export const langs = [
    { code: 'sq-AL', name: 'Albanian' },
    { code: 'eu-ES', name: 'Basque' },
    { code: 'be-BY', name: 'Belarusian' },
    { code: 'bs-BA', name: 'Bosnian' },
    { code: 'bg-BG', name: 'Bulgarian' },
    { code: 'ca-ES', name: 'Catalan' },
    { code: 'hr-HR', name: 'Croatian' },
    { code: 'cs-CZ', name: 'Czech' },
    { code: 'da-DK', name: 'Danish' },
    { code: 'nl-NL', name: 'Dutch' },
    { code: 'en-AU', name: 'English (Australia)' },
    { code: 'en-CA', name: 'English (Canada)' },
    { code: 'en-IN', name: 'English (India)' },
    { code: 'en-NZ', name: 'English (New Zealand)' },
    { code: 'en-ZA', name: 'English (South Africa)' },
    { code: 'en-GB', name: 'English (United Kingdom)' },
    { code: 'en-US', name: 'English (United States)' },
    { code: 'et-EE', name: 'Estonian' },
    { code: 'fo-FO', name: 'Faroese' },
    { code: 'fi-FI', name: 'Finnish' },
    { code: 'fr-FR', name: 'French' },
    { code: 'gl-ES', name: 'Galician' },
    { code: 'de-DE', name: 'German' },
    { code: 'el-GR', name: 'Greek' },
    { code: 'hu-HU', name: 'Hungarian' },
    { code: 'is-IS', name: 'Icelandic' },
    { code: 'ga-IE', name: 'Irish' },
    { code: 'it-IT', name: 'Italian' },
    { code: 'lv-LV', name: 'Latvian' },
    { code: 'lt-LT', name: 'Lithuanian' },
    { code: 'lb-LU', name: 'Luxembourgish' },
    { code: 'mk-MK', name: 'Macedonian' },
    { code: 'mt-MT', name: 'Maltese' },
    { code: 'nb-NO', name: 'Norwegian Bokmål' },
    { code: 'nn-NO', name: 'Norwegian Nynorsk' },
    { code: 'pl-PL', name: 'Polish' },
    { code: 'pt-PT', name: 'Portuguese' },
    { code: 'ro-RO', name: 'Romanian' },
    { code: 'ru-RU', name: 'Russian' },
    { code: 'sr-RS', name: 'Serbian' },
    { code: 'si-LK', name: 'Sinhala' },
    { code: 'sk-SK', name: 'Slovak' },
    { code: 'sl-SI', name: 'Slovenian' },
    { code: 'es-ES', name: 'Spanish' },
    { code: 'sv-SE', name: 'Swedish' },
    { code: 'tr-TR', name: 'Turkish' },
    { code: 'uk-UA', name: 'Ukrainian' },
    { code: 'cy-GB', name: 'Welsh' },
    { code: 'yi', name: 'Yiddish' },
    { code: 'la', name: 'Lingua latīna' }
];
